#macro DAS_SPEED 6
#macro GRID 32
#macro BASE_VAL_SINGLE 40
#macro BASE_VAL_DOUBLE 100
#macro BASE_VAL_TRIPLE 300
#macro BASE_VAL_TETRIS 1200
#macro P2_OFFSET 448
//ONLINE
#macro NET_DISCONNECT 0
#macro NET_CONNECT_SUCCESS 1
#macro NET_MOVE_RIGHT 2
#macro NET_MOVE_LEFT 3
#macro NET_MOVE_DOWN 4
#macro NET_ROTATE_RIGHT 7
#macro NET_ROTATE_LEFT 8
#macro NET_PIECE_SPAWN 9
#macro NET_PIECE_PUT 10
#macro NET_RESTART_SIGNAL 11
#macro NET_RESTART 12
#macro NET_SEND_USERNAME 13
#macro NET_GAMEOVER 14

